name: 'CodeQL'

description: 'Automatically analyze code with CodeQL'

inputs:
  languages:
    description: 'A comma-separated list of CodeQL languages to analyze. Supported languages: cpp, csharp, go, java, javascript, python, ruby'
    required: true
    default: 'java'

outputs:
  results: 
    description: 'A JSON file containing the results of the CodeQL analysis'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run CodeQL analysis
      uses: github/codeql-action/analyze@v2
      with:
        languages: ${{ inputs.languages }}

    - name: Export results to JSON
      uses: github/codeql-action/result-exporter@v1
      with:
        format: sarif
        output_file: results.sarif

    - name: Convert SARIF to JSON
      run: jq -c . < results.sarif > results.json

    - name: Upload CodeQL Analysis Results
      uses: actions/upload-artifact@v2
      with:
        name: codeql-results
        path: results.json
