
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build with Maven
        run: mvn clean install
      - name: Download DesigniteJava
        run: wget "https://www.designite-tools.com/static/download/DJE/DesigniteJava.jar"
      - name: List contents of current directory
        run: |
          pwd
          ls -al
      - name: Analyze project with DesigniteJava
        run: |
          java -jar DesigniteJava.jar -ci -repo $GITHUB_REPOSITORY -pat ${{ secrets.PAT }}
          ls
          ls Designite_output/
          curl -u taranjot20@gmail.com:${{ secrets.GITHUB_TOKEN }} -X PUT -H "Content-Type: multipart/form-data" -F "file=@Designite_output/DesigniteAnalysis.xml" "https://api.github.com/repos/$GITHUB_REPOSITORY/contents/Designite_output/DesigniteAnalysis.xml"
                                               
